{{- if .Values.mysql.enabled }}
{{ $mysqlFullName :=  include "basic-lemp.fullname" . }}
{{ $mysqlFullName := printf "%s-%s" $mysqlFullName "mysql"  }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ $mysqlFullName }}"
  labels:
    {{- include "basic-lemp.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
  selector:
    {{- include "basic-lemp.selectorLabels" . | nindent 4 }}
{{- end }}