apiVersion: v1
kind: Service
metadata:
  name: {{ include "basic-hpa.fullname" . }}
  labels:
    {{- include "basic-hpa.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "basic-hpa.selectorLabels" . | nindent 4 }}
