{{- if .Values.application.hpa.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "lemp.fullname" . }}
  labels:
    {{- include "lemp.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lemp.fullname" . }}
  minReplicas: {{ .Values.application.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.application.hpa.maxReplicas | default 10 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.application.hpa.averageCPUUtilization | default 60 }}
{{- end }}