{{- if .Values.pma.isEnabled  -}}
{{ $pmaFullName :=  include "lemp.fullname" . }}
{{ $pmaFullName := printf "%s-%s" $pmaFullName "pma"  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $pmaFullName }}"
  labels:
    devpanel.com/phpmyadmin-instance: {{ $pmaFullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      devpanel.com/phpmyadmin-instance: {{ $pmaFullName }}
  template:
    metadata:
      labels:
        devpanel.com/phpmyadmin-instance: {{ $pmaFullName }}
    spec:
      containers:
        - name: phpmyadmin
          image: "phpmyadmin/phpmyadmin"
          env:
            - name: PMA_VERBOSE
              value: "{{ .Values.pma.pmgVerbose }}"
            - name: UPLOAD_LIMIT
              value: "{{ .Values.pma.pmaUploadLimit }}"
            - name: PMA_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "lemp.fullname" . }}
                  key: "DB_HOST"
            - name: PMA_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "lemp.fullname" . }}
                  key: "DB_PORT"
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "lemp.fullname" . }}
                  key: "DB_USER"
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "lemp.fullname" . }}
                  key: "DB_PASSWORD"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.pma.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $pmaFullName }}"
  labels:
    devpanel.com/phpmyadmin-instance: {{ $pmaFullName }}
  annotations:
    konghq.com/plugins: "devpanel-kong-jwt"
spec:
  type: "ClusterIP"
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    devpanel.com/phpmyadmin-instance: {{ $pmaFullName }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $pmaFullName }}"
  labels:
    devpanel.com/phpmyadmin-instance: {{ $pmaFullName }}
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  {{- if .Values.pma.secretName }}
  tls:
    - secretName: {{ .Values.pma.secretName | quote }}
      hosts:
        - {{ .Values.pma.hostname | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.pma.hostname | quote }}
      http:
        paths:
          - path: "/"
            backend: 
              serviceName: "{{ $pmaFullName }}"
              servicePort: http
          - path: /devpanel/verify
            backend:
              serviceName: devpanel-authenticator
              servicePort: 8080
{{- end -}}