{{- if eq .Values.application.storageClass "aws-efs" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ include "app.fullname" . }}"
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.application.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-efs
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.application.volumeHandler }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "app.fullname" . }}"
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs
  resources:
    requests:
      storage: {{ .Values.application.storage }}
{{- else }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "app.fullname" . }}"
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.application.storage }}
  storageClassName: {{ .Values.application.storageClass }}
{{- end }}
