{{- if eq .Values.application.storageClass "aws-efs" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ include "lemp.fullname" . }}"
  labels:
    {{- include "lemp.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.application.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-efs
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.application.volumeHandler }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "lemp.fullname" . }}"
  labels:
    {{- include "lemp.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs
  resources:
    requests:
      storage: {{ .Values.application.storage }}
{{- else }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "lemp.fullname" . }}"
  labels:
    {{- include "lemp.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.application.storage }}
  storageClassName: {{ .Values.application.storageClass }}
  {{- if .Values.application.dataSource }}
  dataSource:
    {{- toYaml .Values.application.dataSource | nindent 4 }}
  {{- end }}
{{- end }}

{{- range .Values.application.externalDisks }}
{{- if .enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ include "lemp.fullname" $ }}-{{ .name }}"
  labels:
    {{- include "lemp.labels" $ | nindent 4 }}
spec:
  capacity:
    storage: {{ .storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-efs
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "{{ .volumeHandler }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "lemp.fullname" $ }}-{{ .name }}"
  labels:
    {{- include "lemp.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs
  resources:
    requests:
      storage: {{ .storage }}
{{- end }}
{{- end }}
