{{- if .Values.application.dbName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ .Values.application.dbHost | b64enc | quote }}
  DB_PORT: {{ .Values.application.dbPort | default "3306" | b64enc | quote }}
  DB_NAME: {{ .Values.application.dbName | b64enc | quote }}
  DB_USER: {{ .Values.application.dbUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.application.dbPassword | b64enc | quote }}
{{- end }}