apiVersion: v1
kind: Service
metadata:
  name: {{ include "lemp.fullname" . }}
  labels:
    {{- include "lemp.labels" . | nindent 4 }}
  {{ if .Values.security.basicAuthentication.enabled }}
  annotations:
    konghq.com/plugins: "devpanel-kong-basic-auth"
  {{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.images.nginx.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "lemp.selectorLabels" . | nindent 4 }}
---
{{ if .Values.codeserver.isEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "lemp.fullname" . }}-codeserver"
  labels:
    {{- include "lemp.labels" . | nindent 4 }}
  annotations:
    konghq.com/plugins: "devpanel-kong-jwt"
spec:
  type: "ClusterIP"
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: codeserver
  selector:
    {{- include "lemp.selectorLabels" . | nindent 4 }}
{{- end -}}